### ISSUE TITLE
[Fixed] Issue with redirect from secondary language to main language url

### ISSUE THREAD

**Issue by didoweb** [vigetlabs/craft-localeredirector#10]
I've a multilanguage website with Locale Redirector plugin installed on Craft CMS 2.6.2986.

The site base language is English EN.

When a user come inside the website is will be redirect in base of his browser language settings.

But I find this issue:

If a english user (language EN) comes from an external Italian link the plugin doesn't redirect to the correct URL.

That's what happen:

user clicks this url www.sitename.com/it/slug_italian
and it land in this www.sitename.com/slug_italian
instead he sould land in www.sitename.com/slug_english.
The opposite case, an Italian user click on English link, works well and he is correctly redirected.

Here a pratical example:
https://cycling.favero.com/it/supporto
if you have a browser in english language it not resolve the translation but it show you 404.

**UPDATE**
**_I've update the plugin with the new version and it seems works well!_**

Thanks in advance and regards.

**Comment by jeremyfrank** [comment]
@didoweb What version of Locale Redirector are you using?

**Comment by didoweb** [comment]
**@jeremyfrank** Locale Redirector 1.0.1

Thanks!

**Comment by didoweb** [comment]
Hi,

sorry I've update the plugin with the new version and it seems works well!

Thanks in advance,

D.

**Comment by jeremyfrank** [comment]
No problem! Yeah, version 1.0.2 included a update from a contributor that addressed the differing slug issue.
