### ISSUE TITLE
Problem with the redirect of only two specific url

### ISSUE THREAD

**Issue by didoweb** [vigetlabs/craft-localeredirector#11]
Hi,

I've installed the last version of the plugin and it works well except that two urls.
I've not idea why.

The url is **blog** and **far-q-assioma** and they are located in this website https://cycling.favero.com/.

Blog and Faq are two single pages translated in 5 languages.
The URI in the section's setting is (for FAQ for example):
en -> faq-assioma
it -> faq-assioma
fr -> faq-assioma
es -> faq-assioma
de -> faq-assioma

If I go to the website and I choose Italian language
and after, I try to navigate to https://cycling.favero.com/fr/assioma, it redirects well to the italian version of the page. This page has the same settings of blog and Faq

If I try the same, first selecting Italian language and after, I try navigate to https://cycling.favero.com/fr/faq-assioma, it loads the francais version instead of the Italian version without changing the language cookie setting (it remain IT).

Do you have any suggestion about this?

Thanks in advance and regards,

Davide

**Comment by jeremyfrank** [comment]
There may be a difference between the way entry URIs are accessed from regular sections and single sections. Although, I haven't seen this before. I'll look into it hopefully next week or soon after.

**Comment by didoweb** [comment]
Hi,
thanks a lot. If you need more details don't exitate to ask me.
If you need I can give you an access to the CP of theDev enviroment of the site.

Thanks in advance and regards,

Davide

**Comment by jeremyfrank** [comment]
I have a fix coming soon. It will accommodate single sections like you described, including the homepage which in my environment was redirecting to `/it/__home__`.

**Comment by didoweb** [comment]
Hi, great!
After the fix you update the plugin's release or I take the code into the commits?

Thanks in advance for the support
and brest regards,

Davide

**Comment by jeremyfrank** [comment]
I'll issue a new release so you'll see it show up as an update in the CP of your site.

**Comment by jeremyfrank** [comment]
Let me know if the 1.0.4 update worked for you and if there are any problems. Closing for now.
