### ISSUE TITLE
Error many redirects

### ISSUE THREAD

**Issue by ffranz** [vigetlabs/craft-localeredirector#3]
Hi,
I've just installed the plugin on Craft CMS 2.6.2962 and homepage page isn’t working in console I have an error: net::ERR_TOO_MANY_REDIRECTS

Any idea?
Thanks
F

**Comment by jeremyfrank** [comment]
Sorry for the delay @ffranz. I had some time to look into this today and put out a fix in 27b9dfc209c92ff0964b16298c614787ccd3099b. Give [version 1.0.1](https://github.com/vigetlabs/craft-localeredirector/releases/tag/1.0.1) a try.
