### ISSUE TITLE
404 when other locale's slug is different

### ISSUE THREAD

**Issue by romainpoirier** [vigetlabs/craft-localeredirector#5]
Following the documentation example, this is working fine:

_Requested URL: http://site.com/blog/article-title
Cookie Present: es
Configured Site Locales: en, fr, de, pt, es
Redirects To: http://site.com/es/blog/article-title_

But if the slug of **article-title** is different in **es** locale _(/titulo-del-articulo)_ , the user is redirected to a 404.

The plugin should probably constructs the new URL using original entry id, not using original path.

**Comment by jeremyfrank** [comment]
Thanks for documenting this. I never anticipated the fact that slugs could be different for each locale's version of an entry. I'll take a look at your PR soon!

**Comment by didoweb** [comment]
I've got the same issue,
thanks in advance!

**Comment by jeremyfrank** [comment]
I just merged PR #6 and put out a new release.
