### ISSUE TITLE
Lastsegment bug in newUrl Function

### ISSUE THREAD

**Issue by nivida** [vigetlabs/craft-localeredirector#9]
Hay,

I've the following URL structure: 
/ => de
/fr => fr

It does redirect me to an entry page instead of the home when i enter www.mydomain.de/ or www.mydomain.de/fr but only when i've switched to an other locale and open the startpage in a new Tab.

Fix: 
```php 
private function newUrl($locale)
    {
        $qs = $this->querystring ? '?' . $this->querystring : '';
        $segments = craft()->request->segments;
        $lastSegment = end($segments);
        if ($lastSegment) {
            $criteria = craft()->elements->getCriteria(ElementType::Entry);
            $criteria->slug = $lastSegment;
            $entry = $criteria->first();

            if (!empty($entry)) {
                $new = craft()->elements->getElementById($entry->id, ElementType::Entry, $locale);
                return UrlHelper::getSiteUrl($new->uri, null, null, $locale) . $qs;
            }
            return false;
        }
        return UrlHelper::getSiteUrl('/', null, null, $locale) . $qs;
    }
```

**Comment by boldenamsterdam** [comment]
Same issue here. Fix works. 
@nivida maybe can you ask for a pull request.

**Comment by jeremyfrank** [comment]
@nivida Apologies for the delay here. I'm not seeing this bug in one of my local sites, but it may be using an older version of the plugin. So I'll try to look into this at some point soon.

**Comment by jeremyfrank** [comment]
@nivida I am not experiencing this issue in my local test site. I have English (at "/") Spanish (at "/es") and French (at "/fr"). Can you verify that you are setting the local cookie and handling the redirect on the front-end when you switch to a new language selection?

**Comment by didoweb** [comment]
I've try the same issue with the version 1.02 but the fix works.
Can you update the plugin's release with this fix?

Thanks in advance,

**Comment by jeremyfrank** [comment]
Version updated to 1.0.3 with fix that allows updates to properly show up in the Craft admin.
